### ISSUE TITLE
Issues pinging MX-64 using PingDynamixel example class from Windows

### ISSUE THREAD

**Issue by adamscottv** [ihmcrobotics/ihmc-java-dynamixel-library#1]
I verified connectivity to the bus and the ID from another program.

Here is example PingDynamixel output when there is a dynamixel with ID 1:
No dynamixel at address 1
etc

I don't have a MX-106, just MX-64, but it should be exactly the same protocol.

**Comment by dljsjr** [comment]
Hey @adamscottv,

This code does, in fact, work, but as suggested is only tested on the MX-106.

Can you please provide more information? Did you modify the contents of PingDynamixel at all to match your use case? Did you verify that your motor is on `/dev/ttyUSB0` or are you passing in the device handle as a command line argument? Did you change your baud rate via command line arguments or in the code? There are a lot of variables here, and we'd love to help you get this working.

**Comment by adamscottv** [comment]
Thank you for the response. I'm on Windows, and I'm communicating on "COM3". I know the device and serial connection are correct because if I change it I get a serial port error.

Baud rate is 1000000, and that matches what is set in the Dynamixel's table.

I've tried three different MX-64 and always get "No dynamixel".

When I try with AX servos, I get "Data corruption trying to reach Dynamixel" on the IDs for those actuators (actually it's ID+1, strange), then on the retry it gets "No dynamixel..". So I feel confident that the connection to the bus is working.

So for ID 1 AX I get this:
Data corruption trying to reach Dynamixel 2, retrying
No dynamixel at address 2

If I connect a chain with Dynamixels 2, 3, 4 I get:
Data corruption trying to reach Dynamixel 3, retrying
No dynamixel at address 3
Data corruption trying to reach Dynamixel 4, retrying
Data corruption trying to reach Dynamixel 4, retrying
No dynamixel at address 4
Data corruption trying to reach Dynamixel 5, retrying
Data corruption trying to reach Dynamixel 5, retrying
Data corruption trying to reach Dynamixel 5, retrying
No dynamixel at address 5

I've tried two different MX-28 and get either "No dynamixel" or the same results as with AX (intermittently):
Data corruption trying to reach Dynamixel 2, retrying
No dynamixel at address 2

This behavior is reproducible.  I really want to use this Java library so any help would be greatly appreciated.

**Comment by dljsjr** [comment]
Sweet, thanks for the info, especially the part about being on Windows.

We don't use Dynamixels heavily, we currently only have one robot that has them and they are all MX-106 and we've only tested them on Linux. This is a fairly young library so it will definitely need to grow to be a general purpose Dynamixel lib for Java.

@jespersmith is the original author of the library, he may have some insight. It's possible that this is more of a Windows thing than it is a motor model issue. We'll definitely look in to this though.

**Comment by adamscottv** [comment]
Thank you. I will do some additional debugging on my end as well. I should have time tonight to dig in to it.

**Comment by adamscottv** [comment]
Ok, I just figured something out. If I step through with the debugger, it finds the Dynamixel on address 1. If I run it, it does not find it or gets corrupt data. So it would seem that something is happening too fast. Let me know if you have any ideas about how to avoid this issue.

**Comment by dljsjr** [comment]
That's a pretty fascinating heisenbug. Thanks for the update.

**Comment by adamscottv** [comment]
I was able to fix it, pretty obvious bug once I looked into it. There needs to be some delay between sending and receiving. May not happen as frequently on a slow computer like a lower end ARM, but on a faster machine it fails every time. I'm testing on my desktop with an i7-4790K. I found that 20 milliseconds is enough to reliably prevent it. Could probably be a smaller number on slower CPUs, so it should be configurable. Probably < 5ms on a something like a Raspberry Pi. I would never want it to be zero though. 

```
    sendPacket();
    if (instructionPacket[ID] != BROADCAST_ID) {
        Thread.sleep(20);
        receivePacket(instructionPacket[ID], errorHolder);
    }
```

**Comment by adamscottv** [comment]
Also wanted to say thanks for publishing this library, I really appreciate it.

**Comment by jespersmith** [comment]
Thank you for looking into this. I do not need the sleep under Linux on a i7-4770EQ, so I would like to replicate the issue using a Windows PC and see why the sleep is needed. There is probably a difference between the Linux and Windows serial stack, where the Linux stack blocks till all bytes are written and the windows stack does not block.

We run 100Hz loop rates, so putting a 20ms sleep in will dramatically reduce performance.

Could you provide the following information
- Which Windows version do you use
- Do you use the USB2Dynamixel or another serial port?
- Do you use TTL (3 wire) or RS-485 (4 wire) connection
- What is the return delay time on the MX64 (register 5 (0X05))

**Comment by adamscottv** [comment]
I need to do more testing, last night was just a quick session because I was tired. I should have more time this weekend. And I should have my linux SCB by mid-week.

Windows 8.1
USB2Dynamixel (for now)
TTL
default

**Comment by adamscottv** [comment]
Decided to roll my own library but thanks anway.
